### ISSUE TITLE
Fully automated Report Generation

### ISSUE THREAD

**Issue by SekeunKim** [CarDS-Yale/PanEcho#1]
Thank you for your nice work.

I have one question about your work.

After we collect model output (e.g. LV diameter), what process is followed to make auto report generation in your project page (LLM?)?

Thank you.

**Comment by gholste** [comment]
For that demo, we used a structured template to convert model predictions into the text report. PanEcho is not a generative model, so no LLM involved.

We may release a demo on a partial echo study to demonstrate this entire pipeline (including the report creation) depending on whether we have permission to release anonymized data from our cohort. If we do so, I'll come back to this and let you know.
