### ISSUE TITLE
DICOM pre-processing

### ISSUE THREAD

**Issue by dfpasdel** [CarDS-Yale/PanEcho#2]
Hi, I am very eager to try your model. Could you provide a script to generate the .avi from DICOM files? This is in itself not very difficult, but I ask to make sure that the DICOM files are preprocessed the proper way. Thank you in advance.

**Comment by gholste** [comment]
Thanks for the question. See our prior work on aortic stenosis detection from echocardiograms: https://github.com/CarDS-Yale/echo-severe-AS?tab=readme-ov-file#pipeline. Here we follow a very similar pipeline that involves extracting the pixel data from DICOMs, deidentifying the frames, saving to intermediate .avi files, performing view classification, then preprocessing and splitting the data for model training. Some minor details have changed but the `preprocess.py` script contains the core DICOM extraction code. If we update the preprocessing code for this repo, I will come back to this issue and let you know.
