### ISSUE TITLE
Input size

### ISSUE THREAD

**Issue by SekeunKim** [CarDS-Yale/PanEcho#3]
Can the model be applied to video lengths other than the ones used during training (e.g., B 3 16(fr) x y), such as 32 frames or even 20 frames?

**Comment by gholste** [comment]
Thanks for the question. I have just added support for variable video length through the `clip_len` argument. E.g., to run the model on 32-frame clips you would now run
```
import torch

model = torch.hub.load('CarDS-Yale/PanEcho', 'PanEcho', force_reload=True, clip_len=32)
```

When running direct inference (not fine-tuning), I would recommend using a clip length of 16 in accordance with how the model was trained and evaluated. You are welcome to try other clip lengths, but we cannot make any guarantees about performance, as the model has only seen 16-frame clips. For fine-tuning, I would imagine there is more leeway in using different video lengths.
